{% set name = "opentelemetry-instrumentation-redis" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_redis-{{ version }}.tar.gz
  sha256: c1f461baf6a3b266d4fca5188ab384505a71cc10bf71d32a6784b49d5db822f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.42b0
    - opentelemetry-semantic-conventions ==0.42b0
    - wrapt >=1.12.1
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-sdk ~=1.3
    # - opentelemetry-instrumentation-redis 
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-sdk ~=1.3
    # - opentelemetry-instrumentation-redis 
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-sdk ~=1.3
    # - opentelemetry-instrumentation-redis 
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-sdk ~=1.3
    # - opentelemetry-instrumentation-redis 
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-sdk ~=1.3
    # - opentelemetry-instrumentation-redis 
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-sdk ~=1.3
    # - opentelemetry-instrumentation-redis 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  summary: OpenTelemetry Redis instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
